/*
Google Code Lab 4 - Adding Google Maps to a Flutter App
https://codelabs.developers.google.com/codelabs/google-maps-in-flutter/#0
 */


/*
Todo #1 set API key in android/app/src/main/AndroidManifest.xml
todo #2 set API key in  ios/Runner/AppDelegate.m
todo #3 You also need to add a setting to ios/Runner/Info.plist.
  This entry forces Flutter on iOS into a single threaded mode,
  which is required for the platform view embedding to work.
  This technical restriction is being worked on and will be lifted before
  Google Maps moves out of Developer Preview.

Notice:
run ../flutter/bin/flutter packages pub run build_runner build
to get autogenerated locations.g.dart
 */


import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:code_labs/GoogleCodeLabs/GoogleMapsApp/locations.dart' as locations;

void main() => runApp(GMapsApp());

class GMapsApp extends StatefulWidget {
  @override
  _GMapsAppState createState() => _GMapsAppState();
}

class _GMapsAppState extends State<GMapsApp> {
  final Map<String, Marker> _markers = {};
  Future<void> _onMapCreated(GoogleMapController controller) async {
    final googleOffices = await locations.getGoogleOffices();
    setState(() {
      _markers.clear();
      for (final office in googleOffices.offices) {
        final marker = Marker(
          markerId: MarkerId(office.name),
          position: LatLng(office.lat, office.lng),
          infoWindow: InfoWindow(
            title: office.name,
            snippet: office.address,
          ),
        );
        _markers[office.name] = marker;
      }
    });
  }

  @override
  Widget build(BuildContext context) => MaterialApp(
    home: Scaffold(
      appBar: AppBar(
        title: const Text('Google Office Locations'),
        backgroundColor: Colors.green[700],
      ),
      body: GoogleMap(
        onMapCreated: _onMapCreated,
        initialCameraPosition: CameraPosition(
          target: const LatLng(0, 0),
          zoom: 2,
        ),
        markers: _markers.values.toSet(),
      ),
    ),
  );
}